version: "3.9"
services:
  node-app:
    build: .
    env_file:
      - server-variables.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_tualy
      - POSTGRES_USER=mabravo153
      - POSTGRES_PASSWORD=Barranquilla1.
volumes:
  dbdata:
